version: "3.7"

services:
  db:
    env_file:
      - .env
    image: postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_NAME
    networks:
      - database
    volumes:
      - ./db:/var/lib/postgresql/data
  
  redis:
    container_name: redis-cache
    image: redis:6.0.5
    ports:
      - 6379:6379
    networks:
      - server

  serveur:
    env_file:
      - .env
    image: "node:12.16.3"
    working_dir: /app
    command: bash -c "yarn && yarn dev"
    restart: always
    depends_on:
      - db
    ports:
      - "${API_PORT:-5000}:${API_PORT:-5000}"
    volumes:
      - ./serveur:/app
      - /app/node_modules
    environment:
      PORT: $API_PORT
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      JWTSECRET: $JWTSECRET
      GMAIL_ADDRESS: $GMAIL_ADDRESS
      GMAIL_PASSWORD: $GMAIL_PASSWORD
      REDIS_URL: redis-cache
      REDIS_PORT: 6379
    networks:
      - server
      - database
      - front

  admin:
    env_file:
      - .env
    image: adminer
    restart: always
    depends_on:
      - db
    networks:
      - database
    ports:
      - "${ADMINER_PORT:-5050}:8080"

  client:
    image: "node:12.16.3"
    working_dir: /app
    command: bash -c "yarn && yarn start"
    restart: always
    stdin_open: true
    ports:
      - "${FRONT_PORT:-3000}:3000"
    environment:
      REACT_APP_API_URL: http://localhost:${API_PORT:-5000}
    depends_on:
      - serveur
    volumes:
      - ./client:/app
    networks:
      - front

networks:
  database:
  front:
  server:
