version: "3.7"

services:
  db:
    env_file: 
      - .env
    image: postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_NAME
    networks:
        - database
    volumes:
      - ./db:/var/lib/postgresql/data

  serveur:
    env_file: 
      - .env
    image: "node"
    working_dir: /app
    command: bash -c "yarn && yarn dev"
    restart: always
    depends_on:
      - db
    ports:
      - "${API_PORT:-5000}:${API_PORT:-5000}"
    volumes:
      - ./serveur:/app
    environment:
      PORT: $API_PORT
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
    networks:
      - database
      - front

  admin:
    env_file: 
      - .env
    image: adminer
    restart: always
    depends_on:
      - db
    networks:
      - database
    ports:
      - "${ADMINER_PORT:-5050}:8080"
    
  client:
    image: "node"
    working_dir: /app
    command: bash -c "npm i && npm start"
    restart: always
    ports:
      - "${FRONT_PORT:-3000}:3000"
    environment:
      REACT_APP_API_URL: http://localhost:$API_PORT/api
    depends_on:
      - serveur
    volumes:
      - ./client:/app 
    networks:
      - front

networks:
  database:
  front:
