---
- name: Create Application directory
  file:
    path: /opt/app
    state: directory
  become: yes

- name: Copy docker-compose configuration file
  template:
    src: templates/docker-compose.yml
    dest: /opt/app/docker-compose.yml
  become: yes

- name: Run services
  docker_compose:
    project_name: '{{ site_project_name }}'
    project_src: /opt/app
    pull: yes
  become: yes
  