---

- block:
    - block:
        - name: Check if client directory exists
          stat:
            path: ../client
          register: client_dir

        - name: Clone front if client directory does not exist
          command: git clone https://github.com/ten4ssdp/front-office.git ../client
          when: client_dir.stat.exists == False

        - name: Get front release tag
          command: git describe --abbrev=0 --tags --exact-match
          args:
            chdir: ../client
          register: front_release_tag

        - name: Build front image
          command: docker build -t registry.kevinmanssat.fr/ssdp:{{ front_release_tag.stdout }} ../client

        - name: Push front image on registry
          command: docker push registry.kevinmanssat.fr/ssdp
      run_once: True
      when: app == 'front' or app == 'all'

    - block:
        - name: Check if serveur directory exists
          stat:
            path: ../serveur
          register: server_dir

        - name: Clone back if serveur directory does not exist
          command: git clone https://github.com/ten4ssdp/planning-api.git ../serveur
          when: server_dir.stat.exists == False

        - name: Get server release tag
          command: git describe --abbrev=0 --tags --exact-match
          args:
            chdir: ../serveur
          register: server_release_tag

        - name: Build api image
          command: docker build -t registry.kevinmanssat.fr/ssdpapi:{{ server_release_tag.stdout }} ../serveur

        - name: Push api image on registry
          command: docker push registry.kevinmanssat.fr/ssdpapi
      run_once: True
      when: app == 'back' or app == 'all'
  delegate_to: 127.0.0.1
  become: no
  when: app is defined
