site_project_name: 'Project name'
site_docker_registry: registry.kevinmanssat.fr

# api
site_api_image_name: ssdpapi
site_api_image_version: '{{ server_release.tag }}'
site_api_base_url: 'http://{{ elb_info.elbs[0].canonical_hosted_zone_name }}'
site_api_port: '1234'
site_jwtsecret: azerty
site_api_redis_host: "{{ groups['cluster-example'][0] }}"
site_api_redis_port: '80'

# front
site_front_image_name: ssdp
site_front_image_version: '{{ front_release.tag }}'
site_front_port: '80'

#database
site_db_host: "{{ hostvars[groups['rds'][0]]['ansible_host'] }}"
site_db_port: '5432'
site_db_name: 'ssdp'
site_db_username: 'ssdpuser'
site_db_password: 'ssdpwd'
