---
- name: install python2
  raw: apt update && apt-get -y install python3

- name: Gather facts
  setup:

- name: install packages
  apt:
    pkg:
      - python-setuptools
      - python-pip
      - docker-compose
    state: present
    update_cache: yes
