---
- name: Gather facts
  setup:

- name: install packages
  apt:
    pkg:
      - python3
      - python-setuptools
      - python3-pip
      - docker-compose
    state: present
    update_cache: yes
