version: "2"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "{{ site_db_port }}:5432"
    environment:
      POSTGRES_DB: "{{ site_db_name }}"
      POSTGRES_USER: "{{ site_db_username }}"
      POSTGRES_PASSWORD: "{{ site_db_password }}"
    networks:
      - database
    volumes:
      - ./db:/var/lib/postgresql/data

  api:
    image: registry.kevinmanssat.fr/ssdpapi
    environment:
      PORT: "{{ site_api_port }}"
      DB_HOST: db
      DB_PORT: "{{ site_db_port }}"
      DB_NAME: "{{ site_db_name }}"
      DB_USERNAME: "{{ site_db_username }}"
      DB_PASSWORD: "{{ site_db_password }}"
      JWTSECRET: "{{ site_jwtsecret }}"
    expose:
      - "{{ site_api_port }}"
    ports:
      - "{{ site_api_port }}:{{ site_api_port }}"
    restart: always
    networks:
      - database
      - front

  adminer:
    image: adminer
    restart: always
    depends_on:
      - api
    networks:
      - database
    ports:
      - 5050:8080

  # client:
  #   image: "node"
  #   working_dir: /app
  #   command: bash -c "npm i && npm start"
  #   restart: always
  #   ports:
  #     - "${FRONT_PORT:-3000}:3000"
  #   environment:
  #     REACT_APP_API_URL: http://localhost:$API_PORT/api
  #   depends_on:
  #     - serveur
  #   volumes:
  #     - ./client:/app
  #   networks:
  #     - front

networks:
  database:
  front:
