---
# - hosts: localhost
#   connection: local
#   gather_facts: false
#   tasks:
#     - debug:
#         var: inventory_hostname

- hosts: [tag_stage_production]
  become: yes
  remote_user: ubuntu

  roles:
    - { role: pip, tags: [pip] }
    - { role: docker, tags: [docker]}
    - { role: common, tags: [common]}

- hosts: tag_component_application:&tag_stage_production
  remote_user: ubuntu

  roles:
    - { role: application, tags: [application] }
