---
- hosts: all
  remote_user: admin
  tasks:
    - name: run ssdpapi
      docker_compose:
        project_name: ssdp
        pull: yes
        definition:
          version: "3.7"
          services:
            api:
              image: registry.kevinmanssat.fr/ssdpapi
              environment:
                POSTGRES_DB: ssdp
                POSTGRES_USER: ssdpuser
                POSTGRES_PASSWORD: ssdpwd
                API_PORT: 1234
                DATABASE_HOST: database
                DATABASE_PORT: 5432
                DATABASE_NAME: ssdp
                DATABASE_USERNAME: ssdpuser
                DATABASE_PASSWORD: ssdpwd
              expose:
                - 1234
              ports:
                - 1234:1234
              restart: always
  roles:
    - { role: pip, tag: [pip], become: yes }
    - { role: docker, tag: [docker] }